# Generated by Django 5.0.2 on 2024-02-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='descriptions',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
